### ISSUE TITLE
Unable to Invite

### ISSUE THREAD

**Issue by angsaysroar** [lipowskm/game-deals-discord-bot#2]
I have tried to invite the bot to my server and it is not working. I was able to invite it to one server that mimics my main server because that's where I test bots, however, all attempts to invite to my main server have failed.

Any assistance that you can provide will be greatly appreciated. Thank you!

**Comment by angsaysroar** [comment]
So I noticed that the bot is being invited into the server but immediately being removed and I'm not sure why. I did not have this issue when I added it to my other server.

**Comment by lipowskm** [comment]
@angsaysroar 
Hi, sorry for late reply.

I haven't been contributing to this repository for a while unfortunately, but the bot leaving the server is expected behaviour.
The bot will leave the server immediately after joining if it hasn't enough permissions. When you invite the bot to the server, you need to make sure that you check ALL of the permissions that it's asking for, because all of them are required.

I hope this will solve your issue, but if it doesn't, just let me know, and I will look into this deeper.

**Comment by lipowskm** [comment]
@angsaysroar 
Just a follow up, I've tested it on my side and the bot seems to be working perfectly. So try those permission first :P

**Comment by angsaysroar** [comment]
@lipowskm, thanks for following up. I have confirmed that all permissions are enabled. I am able to invite other bots to my server and even went as far as to remove bots to ensure there wasn't the potential for conflict but the issue persists.

**Comment by lipowskm** [comment]
@angsaysroar 
Is your discord server named `Quinn & Jester` by any chance?
I've got a clear message in logs saying that the bot didn't get sufficient permissions for this server.
I know you did, but can you make sure again that you gave the bot following permissions:
* Manage roles
* Manage channels
* Send messages
* Manage messages

I've also restarted the application, probably won't help much but worth giving a try anyways.

**Comment by lipowskm** [comment]
Follow up: I've also commented out one piece of code that could be responsible for that. Let me know if that helped.

**Comment by angsaysroar** [comment]
I have enabled all permissions and the issue persists. I have attached a screenshot so you can see:

![UTuPMuf](https://user-images.githubusercontent.com/49806822/150070474-f7bffa37-3467-4441-8402-0fb1640f92cc.png)

I am not certain why the bot will not stay in my server.

**Comment by lipowskm** [comment]
@angsaysroar 
Sorry, I've tried my best but I am unable to find a reason for this behaviour, it's really weird.
I am unable to debug properly, since the bot is working on all my servers.

I could debug it further and probably find the solution, but I would need you to add me on your server and give me administrator permissions for a moment.
If you agree on this, text me on Discord: lipowskm#7931 and we can discuss this further.
